# This is a config for E2B sandbox template.
# You can use template ID (0iw1fulp9lkhkstq8boa) or template name (devle-ai-project-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("devle-ai-project-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("devle-ai-project-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('devle-ai-project-2')

team_id = "f89b5efa-10b0-40ff-87bf-f7bfe58ad970"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "devle-ai-project-2"
template_id = "0iw1fulp9lkhkstq8boa"
